language: scala
scala: 2.12.7
jdk: openjdk8

before_install:
  - sudo apt-get -y install nodejs

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - sbt checkAllFormat
  - sbt clean coverage test
  - sbt coverageReport
